YTDLP_COOKIES_CONTENT = """
# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
.youtube.com	TRUE	/	TRUE	0	VISITOR_INFO1_LIVE	tu_valor_aqui
.youtube.com	TRUE	/	TRUE	0	SID	tu_valor_aqui
.youtube.com	TRUE	/	TRUE	0	HSID	tu_valor_aqui
...
"""
